branches:
  only:
  - master
language: python
python:
- 2.7

before_install:
- git submodule update --init --recursive

install:
# Updates the catalog.
- sudo apt-get update -qq
# Installs the packages.
- sudo apt-get install python-pip curl -y
# Installs the Python packages for Pelican.
- pip install -r requirements.txt

script:
# Installs Pelican
- export PYTHONIOENCODING=utf-8
- mkdir output
# Copies the extra directory
- cp -r extra/* output/
# Generates the package
- pelican
- find .

notifications:
  email:
    on_success: always
    on_failure: always

env:
  global:
  - secure: "kl3u5HqlKcL3N57K8DYT2TlJJmfSLgf344Hj4/Bo/xcfnf8K4x9rh7x/mRXcEkjrJ3x8tt/MqXqL9Kp1RD4wbaoTuOsEss2hY3r6xb3fgWzvswW6Ud++pgGiEzZO55Zg1Mf1TVnVYNgWRCRU4wg/WB5j+XKeB6OdFuEGCxuHOxwBxxtQoldUC9CsNUfCL7R5uXeRIgeTo/THZyNXfuolNqlKbclFO4FV7Cv9Z+69Ot1QTKdwwnzonAKzkcJqumJXDEV3s7KV6g30WW6BmuUWnKJY+qiugHLG85m70A0N529sqSbqg+prMWmPWM3y7p2CiErbE4kwJMZDeyErqSGBMo2njL1K8KTwm5zz0B5Oc+2nQmtcRd/+6BRpJ0ve48iLANpWZ9u3xzod+Iq5unnu7sjffubgDcHOTklzAms7FNQabPs18aBK7FQoECAjSpOD//si2Hb4KfmvTQUqfFsOx4zYgCmgiFbDlPWeekT5yrDAs+OBs8Yy5Ke7n2tIHwiRpUZLH9lvHVWfteKzP2qwUKJDFrFUU8ShNuBQ/ZYvheEqyK7tmEl1EU0JMg2DysKEznA1ZaVOUEd1CQmDvS/JGhz2OXivNxilIXIWRtCaMRNsWdmf9MllYOHYnGivvx7YyWWcwERxKb/aMxMGU0mcBS3UrXf0uT9iRVGoQYS3sH8="

after_success: bash deploy.sh


